# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
- python -V
- python -m pip install -U pip
- pip install virtualenv pylint
- pip install -r requirements.txt
- virtualenv venv
- source venv/bin/activate
lint:
  stage: test
  script:
  - pylint tgenv/
run:
  stage: build
  script:
  - python setup.py bdist_wheel
  - pip install dist/*
  artifacts:
    paths:
    - dist/*.whl
pip:
  stage: deploy
  needs:
  - lint
  - run
  script:
  - pip install twine
  - python setup.py sdist
  - twine upload -u=__token__ -p=${PYPI_TOKEN} --skip-existing dist/*
  only:
  - master
